In [117]:
import pandas as pd

df = pd.read_csv('enhanced_student_habits_performance_dataset.csv')
df.head()

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,100000,26,Male,Computer Science,7.645367,3.0,0.1,Yes,70.3,6.2,...,10.9,Co-Learning Group,Yes,High,9,7,8,Reading,3.0,100
1,100001,28,Male,Arts,5.700000,0.5,0.4,No,88.4,7.2,...,8.3,Co-Learning Group,Yes,Low,7,2,10,Reading,6.0,99
2,100002,17,Male,Arts,2.400000,4.2,0.7,No,82.1,9.2,...,8.0,Library,Yes,High,3,9,6,Kinesthetic,7.6,98
3,100003,27,Other,Psychology,3.400000,4.6,2.3,Yes,79.3,4.2,...,11.7,Co-Learning Group,Yes,Low,5,3,10,Reading,3.2,100
4,100004,25,Female,Business,4.700000,0.8,2.7,Yes,62.9,6.5,...,9.4,Quiet Room,Yes,Medium,9,1,10,Reading,7.1,98

In [118]:
df.shape

(80000, 31)

In [95]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [119]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     80000 non-null  int64
 1   age                            80000 non-null  int64
 2   gender                         80000 non-null  object
 3   major                          80000 non-null  object
 4   study_hours_per_day            80000 non-null  float64
 5   social_media_hours             80000 non-null  float64
 6   netflix_hours                  80000 non-null  float64
 7   part_time_job                  80000 non-null  object
 8   attendance_percentage          80000 non-null  float64
 9   sleep_hours                    80000 non-null  float64
 10  diet_quality                   80000 non-null  object
 11  exercise_frequency             80000 non-null  int64
 12  parental_education_level       80000 non-null  object
 13  internet_quality               80000 non-null  object
 14  mental_health_rating           80000 non-null  float64
 15  extracurricular_participation  80000 non-null  object
 16  previous_gpa                   80000 non-null  float64
 17  semester                       80000 non-null  int64
 18  stress_level                   80000 non-null  float64
 19  dropout_risk                   80000 non-null  object
 20  social_activity                80000 non-null  int64
 21  screen_time                    80000 non-null  float64
 22  study_environment              80000 non-null  object
 23  access_to_tutoring             80000 non-null  object
 24  family_income_range            80000 non-null  object
 25  parental_support_level         80000 non-null  int64
 26  motivation_level               80000 non-null  int64
 27  exam_anxiety_score             80000 non-null  int64
 28  learning_style                 80000 non-null  object
 29  time_management_score          80000 non-null  float64
 30  exam_score                     80000 non-null  int64
dtypes: float64(10), int64(9), object(12)
memory usage: 18.9+ MB

student_id                       0
age                              0
gender                           0
major                            0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
previous_gpa                     0
semester                         0
stress_level                     0
dropout_risk                     0
social_activity                  0
screen_time                      0
study_environment                0
access_to_tutoring               0
family_income_range              0
parental_support_level           0
motivation_level                 0
exam_anxiety_score               0
learning_style                   0
time_management_score            0
exam_score                       0
dtype: int64

In [97]:
# Remove unnecessary columns
df = df.drop(columns=['student_id','index', 'attendance_percentage','exercise_frequency','diet_quality','parental_education_level','internet_quality','mental_health_rating','extracurricular_participation','exam_score'], errors='ignore')
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,sleep_hours
0,23,Female,0.0,1.2,1.1,No,8.0
1,20,Female,6.9,2.8,2.3,No,4.6
2,21,Male,1.4,3.1,1.3,No,8.0
3,23,Female,1.0,3.9,1.0,No,9.2
4,19,Female,5.0,4.4,0.5,No,4.9

In [98]:
df.describe()

,age,study_hours_per_day,social_media_hours,netflix_hours,sleep_hours
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,6.470100
std,2.3081,1.46889,1.172422,1.075118,1.226377
min,17.0000,0.00000,0.000000,0.000000,3.200000
25%,18.7500,2.60000,1.700000,1.000000,5.600000
50%,20.0000,3.50000,2.500000,1.800000,6.500000
75%,23.0000,4.50000,3.300000,2.525000,7.300000
max,24.0000,8.30000,7.200000,5.400000,10.000000