In [12]:
import pandas as pd

df = pd.read_csv('student_habits_performance.csv')
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [15]:
# Remove unnecessary columns
df = df.drop(columns=['student_id','index', 'netflix_hours', 'attendance_percentage','exercise_frequency','diet_quality','parental_education_level','internet_quality','mental_health_rating','extracurricular_participation','exam_score'], errors='ignore')
df.head()

,age,gender,study_hours_per_day,social_media_hours,part_time_job,sleep_hours
0,23,Female,0.0,1.2,No,8.0
1,20,Female,6.9,2.8,No,4.6
2,21,Male,1.4,3.1,No,8.0
3,23,Female,1.0,3.9,No,9.2
4,19,Female,5.0,4.4,No,4.9

In [16]:
df.describe()

             age  study_hours_per_day  social_media_hours  sleep_hours
count  1000.0000           1000.00000         1000.000000  1000.000000
mean     20.4980              3.55010            2.505500     6.470100
std       2.3081              1.46889            1.172422     1.226377
min      17.0000              0.00000            0.000000     3.200000
25%      18.7500              2.60000            1.700000     5.600000
50%      20.0000              3.50000            2.500000     6.500000
75%      23.0000              4.50000            3.300000     7.300000
max      24.0000              8.30000            7.200000    10.000000

In [17]:
#removing duplicates
df = df.drop_duplicates()

In [18]:


#remove rows where sleep_hours is too high or too low
Q1 = df['sleep_hours'].quantile(0.25)
Q3 = df['sleep_hours'].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df['sleep_hours'] < (Q1 - 1.5 * IQR)) | (df['sleep_hours'] > (Q3 + 1.5 * IQR)))]

In [19]:
# Remove rows where study_hours_per_day is too high or too low
Q1 = df['study_hours_per_day'].quantile(0.25)
Q3 = df['study_hours_per_day'].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df['study_hours_per_day'] < (Q1 - 1.5 * IQR)) |
          (df['study_hours_per_day'] > (Q3 + 1.5 * IQR)))]

In [20]:
df['focus_ratio'] = df['study_hours_per_day'] / (df['study_hours_per_day'] +
                                                 df['social_media_hours'] + 1)
df['sleep_study_balance'] = df['sleep_hours'] / (df['study_hours_per_day'] + 1)
df['productivity_index'] = df['study_hours_per_day'] * df['focus_ratio']
df.head()

,age,gender,study_hours_per_day,social_media_hours,part_time_job,sleep_hours,focus_ratio,sleep_study_balance,productivity_index
0,23,Female,0.0,1.2,No,8.0,0.000000,8.000000,0.000000
1,20,Female,6.9,2.8,No,4.6,0.644860,0.582278,4.449533
2,21,Male,1.4,3.1,No,8.0,0.254545,3.333333,0.356364
3,23,Female,1.0,3.9,No,9.2,0.169492,4.600000,0.169492
4,19,Female,5.0,4.4,No,4.9,0.480769,0.816667,2.403846

In [21]:
df['task_completed'] = (
    (df['focus_ratio'] >= 0.6) &
    (df['sleep_hours'] >= 6) &
    (df['productivity_index'] >= df['productivity_index'].median())
).astype(int)

In [22]:
df['task_completed'].value_counts()

task_completed
0    855
1    136
Name: count, dtype: int64

In [23]:
df['task_completed'].value_counts(normalize=True)

task_completed
0    0.862765
1    0.137235
Name: proportion, dtype: float64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  991 non-null    int64
 1   gender               991 non-null    object
 2   study_hours_per_day  991 non-null    float64
 3   social_media_hours   991 non-null    float64
 4   part_time_job        991 non-null    object
 5   sleep_hours          991 non-null    float64
 6   focus_ratio          991 non-null    float64
 7   sleep_study_balance  991 non-null    float64
 8   productivity_index   991 non-null    float64
 9   task_completed       991 non-null    int64
dtypes: float64(6), int64(2), object(2)
memory usage: 85.2+ KB

In [25]:
# One-hot encoding for categorical columns
df = pd.get_dummies(df, columns=['gender', 'part_time_job'], drop_first=True)
df.head()

,age,study_hours_per_day,social_media_hours,sleep_hours,focus_ratio,sleep_study_balance,productivity_index,task_completed,gender_Male,gender_Other,part_time_job_Yes
0,23,0.0,1.2,8.0,0.000000,8.000000,0.000000,0,False,False,False
1,20,6.9,2.8,4.6,0.644860,0.582278,4.449533,0,False,False,False
2,21,1.4,3.1,8.0,0.254545,3.333333,0.356364,0,True,False,False
3,23,1.0,3.9,9.2,0.169492,4.600000,0.169492,0,False,False,False
4,19,5.0,4.4,4.9,0.480769,0.816667,2.403846,0,False,False,False

In [26]:
X = df.drop(columns=['task_completed'])
y = df['task_completed']

In [27]:
#split the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [28]:
#smote for traing data
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

In [29]:
#check the balancing
y_train_bal.value_counts()

task_completed
0    683
1    683
Name: count, dtype: int64

In [30]:
#feature scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = [
    'age',
    'study_hours_per_day',
    'social_media_hours',
    'sleep_hours',
    'focus_ratio',
    'sleep_study_balance',
    'productivity_index'
]

X_train_bal[num_cols] = scaler.fit_transform(X_train_bal[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])